/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.sample.petrinet.xpetrinet.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractXPetrinetValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://fr.inria.diverse.sample.petrinet.xpetrinet/petrinet/"));
		return result;
	}
	
}
