/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.sample.petrinet.xpetrinet


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XPetrinetRuntimeModule extends AbstractXPetrinetRuntimeModule {
}
