/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.sample.petrinet.xpetrinet


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XPetrinetStandaloneSetup extends XPetrinetStandaloneSetupGenerated {

	def static void doSetup() {
		new XPetrinetStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
