/*
 * generated by Xtext 2.9.2
 */
package fr.inria.diverse.sample.petrinet.xpetrinet.serializer;

import com.google.inject.Inject;
import fr.inria.diverse.sample.petrinet.xpetrinet.petrinet.Net;
import fr.inria.diverse.sample.petrinet.xpetrinet.petrinet.PetrinetPackage;
import fr.inria.diverse.sample.petrinet.xpetrinet.petrinet.Place;
import fr.inria.diverse.sample.petrinet.xpetrinet.petrinet.Transition;
import fr.inria.diverse.sample.petrinet.xpetrinet.services.XPetrinetGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class XPetrinetSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private XPetrinetGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == PetrinetPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case PetrinetPackage.NET:
				sequence_Net(context, (Net) semanticObject); 
				return; 
			case PetrinetPackage.PLACE:
				sequence_Place(context, (Place) semanticObject); 
				return; 
			case PetrinetPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Net returns Net
	 *
	 * Constraint:
	 *     ((places+=Place places+=Place*)? (transitions+=Transition transitions+=Transition*)?)
	 */
	protected void sequence_Net(ISerializationContext context, Net semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Place returns Place
	 *
	 * Constraint:
	 *     (name=EString initialTokens=EInt?)
	 */
	protected void sequence_Place(ISerializationContext context, Place semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (name=EString input+=[Place|EString] input+=[Place|EString]* output+=[Place|EString] output+=[Place|EString]*)
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
